12720 2016-09-22 13:40:31,270  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
12720 2016-09-22 13:40:34,520 127.0.0.1 - - [22/Sep/2016 13:40:34] "GET / HTTP/1.1" 200 -
12720 2016-09-22 13:40:36,622 Processing: 1
12720 2016-09-22 13:40:36,622 Cant find this PN
12720 2016-09-22 13:40:36,632 Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".\web.py", line 161, in hello
    for i in table_generate(arr):
TypeError: 'NoneType' object is not iterable
12720 2016-09-22 13:40:36,662 127.0.0.1 - - [22/Sep/2016 13:40:36] "POST / HTTP/1.1" 500 -
12720 2016-09-22 13:41:16,058 Processing: 1
12720 2016-09-22 13:41:16,068 Cant find this PN
12720 2016-09-22 13:41:16,068 Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".\web.py", line 161, in hello
    print (arr)
TypeError: 'NoneType' object is not iterable
12720 2016-09-22 13:41:16,088 127.0.0.1 - - [22/Sep/2016 13:41:16] "POST / HTTP/1.1" 500 -
12720 2016-09-22 13:41:18,599 Processing: 1
12720 2016-09-22 13:41:18,599 Cant find this PN
12720 2016-09-22 13:41:18,599 Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".\web.py", line 161, in hello
    print (arr)
TypeError: 'NoneType' object is not iterable
12720 2016-09-22 13:41:18,619 127.0.0.1 - - [22/Sep/2016 13:41:18] "POST / HTTP/1.1" 500 -
